### ISSUE TITLE
Version 1.2.1 is gone from pypi

### ISSUE THREAD

**Issue by jakubman1** [karpierz/pkg_about#1]
Hello.
We use pkg-about as a dependency of the libpcap Python wrapper in our project. Our package manager, PDM, installs fixed versions of all dependencies as specified in our .lock files.

Yesterday, our CI started failing because version 1.2.1 of pkg-about—which our lock files reference—was no longer available on PyPI.

We have since updated our lock files to use a newer version, but we’re concerned about the sudden removal of a specific version without notice. Could you clarify the reason for removing version 1.2.1? Additionally, is there a way to prevent the same issue in the future?

Thank you.

**Comment by karpierz** [comment]
I didn't suppose/had no idea at all that anyone uses pkg_about besides me :(.
Unfortunately I had to delete older versions as they didn't build correctly/caused conflicts with the newest other packages.
Version 1.2.2 is fully compatible with 1.2.1.
However, I recommend the newest one (1.2.5) - also 100% compatible with 1.2.1
I am very sorry again and promise not to remove already published versions without warning. 
PS: in my libpcap a constraint exists like: pkg-about>= so after reinstalling libpcap newest version of pkg_about will be used

**Comment by karpierz** [comment]
@jakubman1 jakubman1
I am closing this issue. In case of problems with pkg_about, please let me know.

**Comment by MrMino** [comment]
@karpierz for the record, seems like libpcap is using this as a dependency, so this is definitely used by people :smiley:.

See https://pypistats.org/packages/pkg-about - ~100k downloads last month :)

PyPI has a functionality called "yanking" that lets you tell the package managers to skip a given package distribution (version) without deleting it from the index completely. See https://pypi.org/help/#yanked.
